##
#  This compose file is used for local development and adapter testing only.
#  See `/docker` for a generic and production-ready docker file
##

version: "3.5"
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbt"
    ports:
      - "5432:5432"

  postgres-dbt:
      image: postgres
      environment:
        POSTGRES_PASSWORD: pssd
        POSTGRES_USER : dbtuser
        POSTGRES_DB : dbtdb
        DBT_SCHEMA: dbt
        DBT_RAW_DATA_SCHEMA: dbt_raw_data
      expose:
        - 5432
      restart: always
      volumes:
        - ./sample_data:/sample_data